name: Pull Request Checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  disable_merge:
    name: Disable Merge Button
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
      contents: read
    steps:
      - name: Set Pending Status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'pending',
              context: 'pr-checks',
              description: 'Waiting for all checks to complete...'
            })

  verify:
    name: Verify Build & Tests
    runs-on: ubuntu-latest
    needs: disable_merge
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > app/google-services.json

      - name: Run unit tests
        run: ./gradlew clean test

      - name: Verify debug build
        run: ./gradlew assembleDebug

      - name: Verify release build
        run: ./gradlew bundleRelease

  enable_merge:
    name: Enable Merge Button
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      pull-requests: write
      statuses: write
      contents: read
    steps:
      - name: Set Success Status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              context: 'pr-checks',
              description: 'All checks passed! Ready to merge.'
            })

  notify_failure:
    name: Notify Failure
    runs-on: ubuntu-latest
    needs: verify
    if: failure()
    permissions:
      pull-requests: write
      statuses: write
      contents: read
    steps:
      - name: Set Failure Status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'failure',
              context: 'pr-checks',
              description: 'Checks failed. Please fix the issues before merging.'
            })