name: Pull Request Checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

# This ensures the merge button is disabled until all checks complete
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify Build & Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
      statuses: write
      contents: read
    steps:
      - name: Pending status
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'pending',
              context: 'merge_group',
              description: 'Checks are running...'
            })

      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > app/google-services.json

      - name: Run unit tests
        run: ./gradlew clean test

      - name: Verify debug build
        run: ./gradlew assembleDebug

      - name: Verify release build
        run: ./gradlew bundleRelease

      - name: Success status
        uses: actions/github-script@v7
        if: success()
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              context: 'merge_group',
              description: 'All checks passed!'
            })

      - name: Failure status
        uses: actions/github-script@v7
        if: failure()
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'failure',
              context: 'merge_group',
              description: 'Checks failed'
            })