name: Release to Google Play

on:
  push:
    branches: [main]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean test

  build-and-deploy:
    name: Build and Deploy to Google Play
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > app/google-services.json

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Android Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEYSTORE }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google play console
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > app/app-release.json

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: app/app-release.json
          packageName: dev.toufikforyou.colormatching
          releaseFiles: app/app-release.aab
          track: draft
          status: complete