name: Release to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      version_name:
        type: string
        required: true
        default: '1.0.0'
        description: 'Version name to be used in release notes'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > app/google-services.json

      - name: Run unit tests
        run: ./gradlew clean test

  build-and-deploy:
    name: Build and Firebase App Distribution
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > app/google-services.json

      - name: Create release directory
        run: mkdir -p app/release

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: ${{ inputs.version_name }}

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Copy AAB to release directory
        run: cp app/build/outputs/bundle/release/*.aab app/release/

      - name: Sign Android Release
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEYSTORE }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS_PASSWORD }}

      - name: Debug Release Files
        run: |
          echo "SIGNED_RELEASE_FILE: $SIGNED_RELEASE_FILE"
          echo "Files in app/release:"
          ls -la app/release/
          echo "Files in app directory:"
          ls -la app/

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_CREDENTIAL_FIREBASE }}
          groups: toufikforyou
          file: ${{ env.SIGNED_RELEASE_FILE }}
          releaseNotes: ${{ inputs.version_name }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version_name }}
          release_name: Release v${{ inputs.version_name }}
          draft: false
          prerelease: false
          body: |
            Release version ${{ inputs.version_name }}
            
            Changes in this release:
            - Automatic build from GitHub Actions
            - Build number: ${{ github.run_number }}

      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/release/app-release-signed.apk
          asset_name: app-v${{ inputs.version_name }}.apk
          asset_content_type: application/vnd.android.package-archive