name: Release to Firebase App Distribution

on:
  workflow_dispatch:

jobs:
#  test:
#    name: Unit Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: 17
#          cache: 'gradle'
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Create Google Play Service Account JSON file
#        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > app/google-services.json
#
#      - name: Run unit tests
#        run: ./gradlew clean test

  build-and-deploy:
    name: Build, GitHub Release, and Firebase Distribution
#    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Google Play Service Account JSON file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > app/google-services.json

      - name: Create release directories
        run: |
          mkdir -p app/release/aab
          mkdir -p app/release/apk

      - name: Generate version name
        id: version
        run: |
          # Get the current year and month in YY.MM format
          YEAR_MONTH=$(date +'%y.%m')
          
          # Count number of tags that start with the current YY.MM
          TAG_COUNT=$(git tag -l "$YEAR_MONTH.*" | wc -l)
          # Increment tag count by 1 (or set to 1 if no matching tags exist)
          TAG_VERSION=$((TAG_COUNT + 1))
          
          # Create version name in format YY.MM.TAG.VERSION_CODE
          VERSION_NAME="${YEAR_MONTH}.${TAG_VERSION}.${{ github.run_number }}"
          
          echo "year_month=$YEAR_MONTH" >> $GITHUB_OUTPUT
          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "Version name: $VERSION_NAME"

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: ${{ steps.version.outputs.version_name }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Copy AAB to release directory
        run: cp app/build/outputs/bundle/release/*.aab app/release/aab/

      - name: Copy APK to release directory
        run: cp app/build/outputs/apk/release/*.apk app/release/apk/

      - name: Sign Android AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/release/aab
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEYSTORE }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS_PASSWORD }}

      - name: Sign Android APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/release/apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEYSTORE }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS_PASSWORD }}

      - name: Debug Release Files
        run: |
          echo "Files in app/release/aab:"
          ls -la app/release/aab/
          echo "Files in app/release/apk:"
          ls -la app/release/apk/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version_name }}
          name: v${{ steps.version.outputs.version_name }}
          draft: false
          prerelease: false
          body: |
            Release version ${{ steps.version.outputs.version_name }}
            
            Changes in this release:
            - Automatic build from GitHub Actions
            - Build number: ${{ github.run_number }}
            - Year.Month: ${{ steps.version.outputs.year_month }}
            - Tag version: ${{ steps.version.outputs.tag_version }}
          files: |
            app/release/aab/*.aab
            app/release/apk/*.apk

      - name: Upload AAB to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_CREDENTIAL_FIREBASE }}
          groups: toufikforyou
          file: app/release/aab/*.aab
          releaseNotes: "Version ${{ steps.version.outputs.version_name }} (AAB)"

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_CREDENTIAL_FIREBASE }}
          groups: toufikforyou
          file: app/release/apk/*.apk
          releaseNotes: "Version ${{ steps.version.outputs.version_name }} (APK)"